@namespace
class SpriteKind:
    Sprite1 = SpriteKind.create()
    Character = SpriteKind.create()
    Boss = SpriteKind.create()

def on_button_pressed():
    animation.run_image_animation(PierreLucCharacter,
        assets.animation("""
            myAnim
        """),
        200,
        True)
controller.any_button.on_event(ControllerButtonEvent.PRESSED, on_button_pressed)

def on_on_score():
    game.game_over(True)
info.on_score(100, on_on_score)

Moving = False
PierreLucCharacter: Sprite = None
info.set_life(3)
tiles.set_current_tilemap(tilemap("""
    level1
"""))
PierreLucCharacter = sprites.create(img("""
        ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................................
            ................f...............
            ...............f................
            ..............ff................
            ...........ffffffff.............
            ..........ff1fffffff............
            .........ff1fffff1fff...........
            ........ffffffffff1fff..........
            .........ffffffffffff...........
            ..........dddddddddd............
            ..........dddddddddd............
            ..........d1fddddf1d............
            ..........d1fddddf1d............
            .......cbbdddd33ddddbbc.........
            .......bdbddddddddddbdb.........
            .......bbbf77777777fbbb.........
            ..........f77777777f............
            ..........ffffffffff............
            ..........faaaaaaaaf............
            ...........ffffffff.............
            ...........f......f.............
            ...........f....................
            ................................
            ................................
            ................................
    """),
    SpriteKind.Character)
controller.move_sprite(PierreLucCharacter, 50, 50)
scene.camera_follow_sprite(PierreLucCharacter)

def on_on_update():
    global Moving
    Moving = controller.left.is_pressed() or (controller.up.is_pressed() or (controller.right.is_pressed() or controller.down.is_pressed()))
    if not (Moving):
        animation.stop_animation(animation.AnimationTypes.ALL, PierreLucCharacter)
game.on_update(on_on_update)
