namespace SpriteKind {
    export const Sprite1 = SpriteKind.create()
    export const Character = SpriteKind.create()
    export const Boss = SpriteKind.create()
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    characterAnimations.setCharacterAnimationsEnabled(PierreLucCharacter, false)
    if (characterAnimations.matchesRule(PierreLucCharacter, characterAnimations.rule(Predicate.FacingLeft))) {
    	
    }
    animation.runImageAnimation(
    PierreLucCharacter,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    500,
    false
    )
})
controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    PierreLucCharacter,
    assets.animation`pdawg`,
    200,
    true
    )
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (PierreLucCharacter.isHittingTile(CollisionDirection.Bottom)) {
        PierreLucCharacter.vy += -100
    }
})
info.onScore(100, function () {
    game.gameOver(true)
})
let Moving = false
let PierreLucCharacter: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
PierreLucCharacter = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................f...............
    ...............f................
    ..............ff................
    ...........ffffffff.............
    ..........ff1fffffff............
    .........ff1fffff1fff...........
    ........ffffffffff1fff..........
    .........ffffffffffff...........
    ..........dddddddddd............
    ..........dddddddddd............
    ..........d1fddddf1d............
    ..........d1fddddf1d............
    .......cbbdddd33ddddbbc.........
    .......bdbddddddddddbdb.........
    .......bbbf77777777fbbb.........
    ..........f77777777f............
    ..........ffffffffff............
    ..........faaaaaaaaf............
    ...........ffffffff.............
    ...........f......f.............
    ...........f....................
    ................................
    ................................
    ................................
    `, SpriteKind.Character)
PierreLucCharacter.ay = 150
controller.moveSprite(PierreLucCharacter, 50, 50)
scene.cameraFollowSprite(PierreLucCharacter)
info.setLife(3)
game.onUpdate(function () {
    Moving = controller.left.isPressed() || (controller.up.isPressed() || (controller.right.isPressed() || controller.down.isPressed()))
    if (!(Moving)) {
        animation.stopAnimation(animation.AnimationTypes.All, PierreLucCharacter)
    }
})
